@authorization = keyboard_cat

### /create
POST http://localhost:3001/course-schedule/create HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{authorization}}

{
  "courseId": "208ebabe-ff03-4d69-ae30-5139464c06ac",
  "classSectionId": "3189f4f3-a160-4752-89b0-71e2cb2e9d7a"
}

### /list
POST http://localhost:3001/course-schedule/list HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{authorization}}

{
  "courseId": "7f0dab83-d03c-4ed3-831e-0a00f35c4572"
}

### /get
POST http://localhost:3001/course-schedule/get HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{authorization}}

{
  "id": "b901efd3-d485-445b-b1c5-3e0dbbe50847"
}

### /update
POST http://localhost:3001/course-schedule/update HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{authorization}}

{
  "id": "b901efd3-d485-445b-b1c5-3e0dbbe50847",
  "day": "MONDAY",
  "from": "16:00",
  "to": "18:00"
}

### /delete
POST http://localhost:3001/course-schedule/delete HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{authorization}}

{
  "id": "e262093d-830c-4d06-9d25-2c7a7b6fd41e"
}