@authorization = keyboard_cat

### /create
POST http://localhost:3001/course/create HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{authorization}}

{
  "programId": "2bb10b1a-bd11-44db-8762-2ffcdf52b172",
  "name": "Introduction To Web Technologies",
  "lecUnit": 4,
  "alias": "ITWT",
  "term": "FIRST"
}

### /list
POST http://localhost:3001/course/list HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{authorization}}

{
  "skip": 0,
  "take": 10,
  "term": "FIRST",
  "keywords": ["introduction"]
}

### /get
POST http://localhost:3001/course/get HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{authorization}}

{
  "id": "208ebabe-ff03-4d69-ae30-5139464c06ac"
}

### /update
POST http://localhost:3001/course/update HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{authorization}}

{
  "id": "208ebabe-ff03-4d69-ae30-5139464c06ac",
  "name": "Introduction To Web Technologies (Updated)",
  "alias": "ITWT (Updated)"
}

### /delete
POST http://localhost:3001/course/delete HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{authorization}}

{
  "id": "861e2e4e-c614-4a33-a018-98be504b3a66"
}