@authorization = keyboard_cat

### /create
POST http://localhost:3001/program/create HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{authorization}}

{
  "name": "Bachelor of Science in Information Technology",
  "alias": "BSIT",
  "color": "slate-900",
  "yearCount": 4
}

### /list
POST http://localhost:3001/program/list HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{authorization}}

{
  "skip": 0,
  "take": 10,
  "keywords": ["bachelor"]
}

### /get
POST http://localhost:3001/program/get HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{authorization}}

{
  "id": "7fe97ce1-6979-4acf-b614-58e9807817da"
}

### /update
POST http://localhost:3001/program/update HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{authorization}}

{
  "id": "7fe97ce1-6979-4acf-b614-58e9807817da",
  "name": "Bachelor of Science in Information Technology (Updated)",
  "enabled": false,
  "alias": "BSIT (Updated)",
  "color": "blue-500"
}

### /delete
POST http://localhost:3001/program/delete HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{authorization}}

{
  "id": "ac62797f-51a6-4b72-8f50-9c31a6a21fb7"
}
