@authorization = keyboard_cat

### /list
POST http://localhost:3001/user/list HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{authorization}}

{
  "role": ["ADMIN", "REGISTRY", "STUDENT"],
  "skip": 0,
  "take": 10,
  "keywords": ["jomariel", "gaitera", "test"]
}

### /get
POST http://localhost:3001/user/get HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{authorization}}

{
  "id": "4ded99e8-ee3a-4470-ad17-1b073c03eee7"
}

### /current
GET http://localhost:3001/user/current HTTP/1.1
Authorization: Bearer {{authorization}}

### /update
POST http://localhost:3001/user/update HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{authorization}}

{
  "id": "553003d5-060c-445e-b35f-85d66abd6bb5",
  "enabled": true,
  "UserLevel": {
    "role": "STUDENT"
  },
  "StudentInformation": {
    "studentType": "REGULAR",
    "gender": "MALE",
    "address": "lorem upsum donor amet",
    "programId": "7fe97ce1-6979-4acf-b614-58e9807817da",
    "classSectionId": "3189f4f3-a160-4752-89b0-71e2cb2e9d7a"
  }
}
