@authorization = keyboard_cat

### /list
POST http://localhost:3001/user/list HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{authorization}}

{
  "role": ["ADMIN", "REGISTRY"],
  "skip": 0,
  "take": 10,
  "keyword": "j",
  "departmentId": "01b30971-f728-4fe5-ab7f-82a7f51a8e9f"
}

### /get
POST http://localhost:3001/user/get HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{authorization}}

{
  "id": "01b30971-f728-4fe5-ab7f-82f7f51a8e9b"
}

### /toggle
POST http://localhost:3001/user/toggle HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{authorization}}

{
  "id": "01b30971-f728-4fe5-ab7f-82f7f51a8e9b",
  "state": false
}

### /set-role
POST http://localhost:3001/user/set-role HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{authorization}}

{
  "id": "01b30971-f728-4fe5-ab7f-82f7f51a8e9b",
  "email": "jagaitera1@paterostechnologicalcollege.edu.ph",
  "role": "REGISTRY"
}

### /remove-role
POST http://localhost:3001/user/remove-role HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{authorization}}

{
  "id": "01b30971-f728-4fe5-ab7f-82f7f51a8e9b",
  "email": "jagaitera1@paterostechnologicalcollege.edu.ph"
}
